spring:
  application:
    name: JOB-CENTER
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

server:
  port: 8080


feign:
  client:
    default:
      readTimeout: 20000

ribbon:
  ReadTimeout: 20000